version: '3.8'
services:
  web-app:
    build: .        # Procura o 'dockerfile' na pasta atual
    ports:
      - "5000:5000" # Mapeia Porta PC : Porta Container
    environment:
      - USER_NAME=Alexandre-DevOps